;@generated-datagen-start----------------
; This code was generated by Amiga Assembly extension
;
;----- parameters : modify ------
;expression(x as variable): round(sin(x*pi/180)*pow(2,14))
;variable:
;   name:x
;   startValue:0
;   endValue:10
;   step:1
;outputType(B,W,L): W
;outputInHex: true
;valuesPerLine: 0
;--------------------------------
;- DO NOT MODIFY folowing lines -
;@generated-datagen-end----------------
